import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { fetchCodeRepos } from '../../src/api/fetchCodeRepos.js';
import { handleError } from '../../src/ui/render.js';

// Mock the internal dependencies
vi.mock('../../src/utils/normalizeTag.js', () => ({
    normalizeTag: vi.fn((tag) => [tag.toLowerCase()]),
    filterDisplayTags: vi.fn((rawTags) => (rawTags || []).filter(t => !t.includes(':')))
}));
vi.mock('../../src/ui/render.js', () => ({
    handleError: vi.fn()
}));
vi.mock('../../src/utils/defineRibbonVals.js', () => ({
    getPlatformDisplay: vi.fn(() => 'GitHub')
}));

describe('fetchCodeRepos', () => {
    const originalFetch = global.fetch;

    beforeEach(() => {
        global.fetch = vi.fn();
    });
    afterEach(() => {
        global.fetch = originalFetch;
        vi.clearAllMocks();
    });

    const orgApiUrl = 'https://api.github.com/orgs/test-org/repos';
    const repoApiUrl = 'https://api.github.com/repos/';
    const refreshIntervalDays = 30;
    const releasesMap = {};

    // Generate reliable relative timestamps so tests don't break as time passes
    const now = new Date();
    const recentDateISO = new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString();   // 2 days ago
    const oldDateISO = new Date(now.getTime() - 45 * 24 * 60 * 60 * 1000).toISOString();    // 45 days ago
    const oldestDateISO = new Date(now.getTime() - 90 * 24 * 60 * 60 * 1000).toISOString(); // 90 days ago

    it('maps raw repo data and attaches release data from releasesMap', async () => {
        // Mock a single page GitHub response
        global.fetch.mockResolvedValueOnce({
            ok: true,
            headers: { get: () => null }, // No 'link' header means no pagination
            json: () => Promise.resolve([{
                full_name: 'test-org/code-repo',
                name: 'code-repo',
                updated_at: now.toISOString(),
                created_at: recentDateISO,
                topics: ['python'],
                stargazers_count: 42,
            }])
        });

        // Mock releases map generated by scripts/fetch-releases.js
        const mockReleasesMap = {
            'test-org/code-repo': { tag: 'v1.0', url: 'http://...', isNew: true }
        };

        const items = await fetchCodeRepos(
            'github',
            [], // No additional repos
            orgApiUrl,
            repoApiUrl,
            refreshIntervalDays,
            mockReleasesMap
        );

        expect(items).toHaveLength(1);
        expect(items[0].repoType).toBe('code');
        expect(items[0].hasNewRelease).toBe(true);
        expect(items[0].latestReleaseTag).toBe('v1.0');
        expect(items[0].tags).toContain('python');
        expect(items[0].cardData.pretty_name).toBe('code-repo');
        expect(items[0].cardData.stars).toBe(42);
    });

    // Pagination test: simulate multiple pages of GitHub API results using the Link header
    it('handles multi-page pagination', async () => {
        global.fetch.mockImplementation((url) => {
            if (url === orgApiUrl) {
                // Page 1 setup with Link header pointing to Page 2
                return Promise.resolve({
                    ok: true,
                    headers: {
                        get: (name) => name.toLowerCase() === 'link'
                            ? `<${orgApiUrl}?page=2>; rel="next"`
                            : null
                    },
                    json: () => Promise.resolve([{
                        full_name: 'test-org/repo-page1',
                        name: 'repo-page1',
                        created_at: recentDateISO,
                        updated_at: recentDateISO
                    }])
                });
            } else if (url === `${orgApiUrl}?page=2`) {
                // Page 2 setup with no Link header (breaks loop)
                return Promise.resolve({
                    ok: true,
                    headers: { get: () => null },
                    json: () => Promise.resolve([{
                        full_name: 'test-org/repo-page2',
                        name: 'repo-page2',
                        created_at: recentDateISO,
                        updated_at: recentDateISO }])
                });
            }
        });

        const items = await fetchCodeRepos(
            'github',
            [],
            orgApiUrl,
            repoApiUrl,
            refreshIntervalDays,
            releasesMap);

        expect(global.fetch).toHaveBeenCalledTimes(2);
        expect(global.fetch).toHaveBeenNthCalledWith(1, orgApiUrl);
        expect(global.fetch).toHaveBeenNthCalledWith(2, `${orgApiUrl}?page=2`);
        expect(items).toHaveLength(2);
        expect(items.map(i => i.id)).toEqual(['test-org/repo-page1', 'test-org/repo-page2']);
        expect(items[0].cardData.pretty_name).toBe('repo-page1');
        expect(items[1].cardData.pretty_name).toBe('repo-page2');
    });

    // Test additional repos fetching and merging with org repos
    it('fetches additional org repos once and fetches external repos', async () => {
        // Base organization discovery lists 'test-org/internal-additional'
        const mockOrgRepo = {
            full_name: 'test-org/internal-additional',
            name: 'internal-additional',
            created_at: recentDateISO,
            updated_at: recentDateISO
        };

        const mockExternalRepo = {
            full_name: 'external-org/external-additional',
            name: 'external-additional',
            created_at: recentDateISO,
            updated_at: recentDateISO
        };

        global.fetch.mockImplementation((url) => {
            if (url === orgApiUrl) {
                return Promise.resolve({
                    ok: true,
                    headers: { get: () => null },
                    json: () => Promise.resolve([mockOrgRepo])
                });
            }
            if (url === `${repoApiUrl}external-org/external-additional`) {
                return Promise.resolve({
                    ok: true,
                    headers: { get: () => null },
                    json: () => Promise.resolve(mockExternalRepo)
                });
            }
        });

        const additionalRepos = [
            'test-org/internal-additional',
            'external-org/external-additional'
        ];

        const items = await fetchCodeRepos(
            'github',
            additionalRepos,
            orgApiUrl,
            repoApiUrl,
            refreshIntervalDays,
            releasesMap
        );

        /** Fetch should only be triggered twice: Once for org list, once for external repo.
        * The internal-additional repo is found inside the cache,
        * should not hit the network a second time.
        */
        expect(global.fetch).toHaveBeenCalledTimes(2);
        expect(global.fetch).not.toHaveBeenCalledWith(
            `${repoApiUrl}test-org/internal-additional`
        );

        /** Assert deduplication: 'test-org/internal-additional' in both core lists,
         * shouldn't show up twice in processed outputs.
         */
        expect(items).toHaveLength(2);
        expect(items.map(i => i.id)).toContain('test-org/internal-additional');
        expect(items.map(i => i.id)).toContain('external-org/external-additional');
    });

    // Test that forks and .github repos are excluded from the final list
    it('excludes repository targets designated as forks and .github', async () => {
        global.fetch.mockResolvedValueOnce({
            ok: true,
            headers: { get: () => null },
            json: () => Promise.resolve([
                {
                    full_name: 'test-org/valid-repo',
                    name: 'valid-repo',
                    fork: false,
                    created_at: recentDateISO,
                    updated_at: recentDateISO
                },
                {
                    full_name: 'test-org/forked-repo',
                    name: 'forked-repo',
                    fork: true,
                    created_at: recentDateISO,
                    updated_at: recentDateISO
                },
                {
                    full_name: 'test-org/forked-in-list',
                    name: 'forked-in-list',
                    fork: true,
                    created_at: recentDateISO,
                    updated_at: recentDateISO
                },
                {
                    full_name: 'test-org/.github',
                    name: '.github',
                    fork: false,
                    created_at: recentDateISO,
                    updated_at: recentDateISO
                }
            ])
        });

        const additionalRepos = [
            'test-org/forked-in-list' // This is a fork, but listed to include
        ];

        const items = await fetchCodeRepos(
            'github',
            additionalRepos,
            orgApiUrl,
            repoApiUrl,
            refreshIntervalDays,
            releasesMap);

        expect(items).toHaveLength(2); // Should only include valid-repo and forked-in-list
        expect(items.map(i => i.id)).toContain('test-org/valid-repo');
        expect(items.map(i => i.id)).toContain('test-org/forked-in-list');
        expect(items.map(i => i.id)).not.toContain('test-org/forked-repo');
        expect(items.map(i => i.id)).not.toContain('test-org/.github');
    });

    // Test that isNew flag is set correctly based on creation date and refresh interval
    it('flags items as new based on evaluation thresholds', async () => {
        global.fetch.mockResolvedValueOnce({
            ok: true,
            headers: { get: () => null },
            json: () => Promise.resolve([
                {
                    full_name: 'test-org/new-repo',
                    name: 'new-repo',
                    created_at: recentDateISO,
                    updated_at: now.toISOString()
                },
                {
                    full_name: 'test-org/old-repo',
                    name: 'old-repo',
                    created_at: oldestDateISO,
                    updated_at: oldDateISO
                }
            ])
        });

        const items = await fetchCodeRepos(
            'github',
            [],
            orgApiUrl,
            repoApiUrl,
            refreshIntervalDays,
            releasesMap
        );

        const newRepo = items.find(i => i.id === 'test-org/new-repo');
        const oldRepo = items.find(i => i.id === 'test-org/old-repo');

        expect(newRepo.isNew).toBe(true);
        expect(oldRepo.isNew).toBe(false);
    });

    // Test that network errors are handled gracefully and trigger UI error handling
    it('handles network errors gracefully', async () => {
        // Force the main fetch to fail
        global.fetch.mockResolvedValueOnce({
            ok: false,
            status: 404,
            headers: { get: () => null }
        });

        const items = await fetchCodeRepos(
            'github',
            [],
            orgApiUrl,
            repoApiUrl,
            refreshIntervalDays,
            releasesMap
        );

        expect(handleError).toHaveBeenCalledWith(
            expect.any(Error),
            expect.stringContaining('Failed to fetch code from github')
        );
        expect(items).toEqual([]);
    });

});
