import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { fetchCodeRepos } from '../../src/api/fetchCodeRepos.js';
import { handleError } from '../../src/ui/render.js';
import { getPlatformVals, getPlatformApiUrls } from '../../src/utils/definePlatformVals.js';

// Mock the internal dependencies
vi.mock('../../src/utils/normalizeTag.js', () => ({
    normalizeTag: vi.fn((tag) => [tag.toLowerCase()]),
    filterDisplayTags: vi.fn((rawTags) => (rawTags || []).filter(t => !t.includes(':')))
}));
vi.mock('../../src/ui/render.js', () => ({
    handleError: vi.fn()
}));

const SUPPORTED_PLATFORMS = ['github', 'gitlab', 'codeberg'];
const TEST_ORG = 'test-org';

const platformConfigs = SUPPORTED_PLATFORMS.map(platform => {
    const platformVals = getPlatformVals(platform);
    const urls = getPlatformApiUrls(platform, TEST_ORG);

    return {
        name: platform,
        orgApiUrl: urls.org,
        repoApiUrl: urls.repo,
        starsKey: platformVals.starsKey,
        platformProfileRepo: platformVals.profileRepo,
        forkKey: platformVals.forkKey,
        fullNameKey: platformVals.fullNameKey,
        updatedAtKey: platformVals.updatedAtKey,
        urlKey: platformVals.urlKey,
        encodeRepoId: platformVals.encodeRepoId // used only for GitLab Additional Repos
    };
});

const getMockForkValue = (isFork, platform) => {
    if (!isFork) {
        // GitLab leaves non-forks as undefined; GitHub/Codeberg return false
        return platform === 'gitlab' ? undefined : false;
    }
    // GitLab returns parent project object; GitHub/Codeberg return true
    return platform === 'gitlab' ? { id: 999 } : true;
};

describe.each(platformConfigs)('fetchCodeRepos - $name', (platformConfig) => {
    const originalFetch = global.fetch;

    beforeEach(() => {
        global.fetch = vi.fn();
    });
    afterEach(() => {
        global.fetch = originalFetch;
        vi.clearAllMocks();
    });

    const orgApiUrl = platformConfig.orgApiUrl;
    const repoApiUrl = platformConfig.repoApiUrl;
    const platform = platformConfig.name;
    const starsKey = platformConfig.starsKey;
    const platformProfileRepo = platformConfig.platformProfileRepo;
    const forkKey = platformConfig.forkKey;
    const fullNameKey = platformConfig.fullNameKey;
    const updatedAtKey = platformConfig.updatedAtKey;
    const urlKey = platformConfig.urlKey;
    const encodeRepoId = platformConfig.encodeRepoId;
    const refreshIntervalDays = 30;
    const releasesMap = {};

    // Generate reliable relative timestamps so tests don't break as time passes
    const now = new Date();
    const recentDateISO = new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString();   // 2 days ago
    const oldDateISO = new Date(now.getTime() - 45 * 24 * 60 * 60 * 1000).toISOString();    // 45 days ago
    const oldestDateISO = new Date(now.getTime() - 90 * 24 * 60 * 60 * 1000).toISOString(); // 90 days ago

    it('maps raw repo data, resolves platform keys, and attaches release data', async () => {
        // Mock a single page platform response
        global.fetch.mockResolvedValueOnce({
            ok: true,
            headers: { get: () => null }, // No 'link' header means no pagination
            json: () => Promise.resolve([{
                [fullNameKey]: 'test-org/code-repo',
                name: 'code-repo',
                description: 'A test repository',
                [forkKey]: getMockForkValue(false, platform),
                [updatedAtKey]: now.toISOString(),
                created_at: recentDateISO,
                topics: ['python'],
                [starsKey]: 42,
                [urlKey]: 'http://example.com/test-org/code-repo'
            }])
        });

        // Mock releases map generated by scripts/fetch-releases.js
        const mockReleasesMap = {
            'test-org/code-repo': { tag: 'v1.0', url: 'http://...', isNew: true }
        };

        const items = await fetchCodeRepos(
            platform,
            [], // No additional repos
            orgApiUrl,
            repoApiUrl,
            refreshIntervalDays,
            mockReleasesMap
        );

        expect(items).toHaveLength(1);
        expect(items[0].id).toBe('test-org/code-repo');
        expect(items[0].repoType).toBe('code');
        expect(items[0].description).toBe('A test repository');
        // fork is used for inclusion filtering only and is not returned by fetchCodeRepos
        expect(items[0].lastModified).toStrictEqual(now);
        expect(items[0].hasNewRelease).toBe(true);
        expect(items[0].latestReleaseTag).toBe('v1.0');
        expect(items[0].tags).toContain('python');
        expect(items[0].html_url).toBe('http://example.com/test-org/code-repo');

        expect(items[0].cardData.pretty_name).toBe('code-repo');
        expect(items[0].cardData.stars).toBe(42);

        expect(global.fetch).toHaveBeenCalledTimes(1);
        expect(global.fetch).toHaveBeenCalledWith(orgApiUrl);
    });

    // Pagination test: simulate multiple pages of API results using the Link header
    it('handles multi-page pagination', async () => {
        global.fetch.mockImplementation((url) => {
            if (url === orgApiUrl) {
                // Page 1 setup with Link header pointing to Page 2
                return Promise.resolve({
                    ok: true,
                    headers: {
                        get: (name) => name.toLowerCase() === 'link'
                            ? `<${orgApiUrl}?page=2>; rel="next"`
                            : null
                    },
                    json: () => Promise.resolve([{
                        [fullNameKey]: 'test-org/repo-page1',
                        name: 'repo-page1',
                        created_at: recentDateISO,
                        [updatedAtKey]: recentDateISO
                    }])
                });
            } else if (url === `${orgApiUrl}?page=2`) {
                // Page 2 setup with no Link header (breaks loop)
                return Promise.resolve({
                    ok: true,
                    headers: { get: () => null },
                    json: () => Promise.resolve([{
                        [fullNameKey]: 'test-org/repo-page2',
                        name: 'repo-page2',
                        created_at: recentDateISO,
                        [updatedAtKey]: recentDateISO }])
                });
            }
        });

        const items = await fetchCodeRepos(
            platform,
            [],
            orgApiUrl,
            repoApiUrl,
            refreshIntervalDays,
            releasesMap);

        expect(global.fetch).toHaveBeenCalledTimes(2);
        expect(global.fetch).toHaveBeenNthCalledWith(1, orgApiUrl);
        expect(global.fetch).toHaveBeenNthCalledWith(2, `${orgApiUrl}?page=2`);
        expect(items).toHaveLength(2);
        expect(items.map(i => i.id)).toEqual(['test-org/repo-page1', 'test-org/repo-page2']);
        expect(items[0].cardData.pretty_name).toBe('repo-page1');
        expect(items[1].cardData.pretty_name).toBe('repo-page2');
    });

    // Test additional repos fetching and merging with org repos
    it('fetches additional org repos once and fetches external repos', async () => {
        // Base organization discovery lists 'test-org/internal-additional'
        const mockOrgRepo = {
            [fullNameKey]: 'test-org/internal-additional',
            name: 'internal-additional',
            created_at: recentDateISO,
            [updatedAtKey]: recentDateISO
        };

        const externalRepoId = 'external-org/external-additional';
        const expectedExternalRepoUrl = `${repoApiUrl}${encodeRepoId(externalRepoId)}`;

        const mockExternalRepo = {
            [fullNameKey]: externalRepoId,
            name: 'external-additional',
            created_at: recentDateISO,
            [updatedAtKey]: recentDateISO
        };

        global.fetch.mockImplementation((url) => {
            if (url === orgApiUrl) {
                return Promise.resolve({
                    ok: true,
                    headers: { get: () => null },
                    json: () => Promise.resolve([mockOrgRepo])
                });
            }
            if (url === expectedExternalRepoUrl) {
                return Promise.resolve({
                    ok: true,
                    headers: { get: () => null },
                    json: () => Promise.resolve(mockExternalRepo)
                });
            }
        });

        const additionalRepos = [
            'test-org/internal-additional',
            externalRepoId
        ];

        const items = await fetchCodeRepos(
            platform,
            additionalRepos,
            orgApiUrl,
            repoApiUrl,
            refreshIntervalDays,
            releasesMap
        );

        /** Fetch should only be triggered twice: Once for org list, once for external repo.
        * The internal-additional repo is found inside the cache,
        * should not hit the network a second time.
        */
        expect(global.fetch).toHaveBeenCalledTimes(2);
        expect(global.fetch).toHaveBeenCalledWith(
            `${expectedExternalRepoUrl}`
        );
        expect(global.fetch).not.toHaveBeenCalledWith(
            `${repoApiUrl}test-org/internal-additional`
        );

        /** Assert deduplication: 'test-org/internal-additional' in both core lists,
         * shouldn't show up twice in processed outputs.
         */
        expect(items).toHaveLength(2);
        expect(items.map(i => i.id)).toContain('test-org/internal-additional');
        expect(items.map(i => i.id)).toContain(externalRepoId);
    });

    // Test that forks and platform profile repos are excluded from the final list
    it('excludes repository targets designated as forks and platform profile repos', async () => {
        global.fetch.mockResolvedValueOnce({
            ok: true,
            headers: { get: () => null },
            json: () => Promise.resolve([
                {
                    [fullNameKey]: 'test-org/valid-repo',
                    name: 'valid-repo',
                    [forkKey]: getMockForkValue(false, platform),
                    created_at: recentDateISO,
                    [updatedAtKey]: recentDateISO
                },
                {
                    [fullNameKey]: 'test-org/forked-repo',
                    name: 'forked-repo',
                    [forkKey]: getMockForkValue(true, platform),
                    created_at: recentDateISO,
                    [updatedAtKey]: recentDateISO
                },
                {
                    [fullNameKey]: 'test-org/forked-in-list',
                    name: 'forked-in-list',
                    [forkKey]: getMockForkValue(true, platform),
                    created_at: recentDateISO,
                    [updatedAtKey]: recentDateISO
                },
                {
                    [fullNameKey]: `test-org/${platformProfileRepo}`,
                    name: platformProfileRepo,
                    [forkKey]: getMockForkValue(false, platform),
                    created_at: recentDateISO,
                    [updatedAtKey]: recentDateISO
                }
            ])
        });

        const additionalRepos = [
            'test-org/forked-in-list' // This is a fork, but listed to include
        ];

        const items = await fetchCodeRepos(
            platform,
            additionalRepos,
            orgApiUrl,
            repoApiUrl,
            refreshIntervalDays,
            releasesMap);

        expect(items).toHaveLength(2); // Should only include valid-repo and forked-in-list
        expect(items.map(i => i.id)).toContain('test-org/valid-repo');
        expect(items.map(i => i.id)).toContain('test-org/forked-in-list');
        expect(items.map(i => i.id)).not.toContain('test-org/forked-repo');
        expect(items.map(i => i.id)).not.toContain(`test-org/${platformProfileRepo}`);
    });

    // Test that isNew flag is set correctly based on creation date and refresh interval
    it('flags items as new based on evaluation thresholds', async () => {
        global.fetch.mockResolvedValueOnce({
            ok: true,
            headers: { get: () => null },
            json: () => Promise.resolve([
                {
                    [fullNameKey]: 'test-org/new-repo',
                    name: 'new-repo',
                    created_at: recentDateISO,
                    [updatedAtKey]: now.toISOString()
                },
                {
                    [fullNameKey]: 'test-org/old-repo',
                    name: 'old-repo',
                    created_at: oldestDateISO,
                    [updatedAtKey]: oldDateISO
                }
            ])
        });

        const items = await fetchCodeRepos(
            platform,
            [],
            orgApiUrl,
            repoApiUrl,
            refreshIntervalDays,
            releasesMap
        );

        const newRepo = items.find(i => i.id === 'test-org/new-repo');
        const oldRepo = items.find(i => i.id === 'test-org/old-repo');

        // check that the lastModified dates are set correctly based on the platform-specific updatedAtKey
        expect(items[0].lastModified).toStrictEqual(now);
        expect(items[1].lastModified).toStrictEqual(new Date(oldDateISO));
        expect(newRepo.isNew).toBe(true);
        expect(oldRepo.isNew).toBe(false);
    });

    // Test that network errors are handled gracefully and trigger UI error handling
    it('handles network errors gracefully', async () => {
        // Force the main fetch to fail
        global.fetch.mockResolvedValueOnce({
            ok: false,
            status: 404,
            headers: { get: () => null }
        });

        const items = await fetchCodeRepos(
            platform,
            [],
            orgApiUrl,
            repoApiUrl,
            refreshIntervalDays,
            releasesMap
        );

        expect(handleError).toHaveBeenCalledWith(
            expect.any(Error),
            expect.stringContaining(`Failed to fetch code from ${platform}`)
        );
        expect(items).toEqual([]);
    });

});
